home: # Nom que je donne a la route
    path: / # mon url, ce que je tape après https://localhost:8000/ ...
    controller: App\Controller\DefaultController::home # Fonction a executer

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact